#This file stores configuration options for Iris, such as the currently active shaderpack
#Fri Sep 25 22:33:23 EEST 2026
allowUnknownShaders=false
colorSpace=SRGB
disableUpdateMessage=false
enableDebugOptions=false
enableShaders=true
maxShadowRenderDistance=17
shaderPack=
